from __future__ import annotations

import os
import re
import sqlite3
from collections.abc import Iterator, Mapping
from pathlib import Path
from typing import Any

try:
    import psycopg
    from psycopg.rows import dict_row
    from psycopg.errors import IntegrityError as PostgresIntegrityError
    from psycopg.errors import OperationalError as PostgresOperationalError
except ImportError:  # pragma: no cover - optional dependency until postgres is enabled
    psycopg = None
    dict_row = None
    PostgresIntegrityError = RuntimeError
    PostgresOperationalError = RuntimeError


SQLITE_BACKEND = "sqlite"
POSTGRES_BACKEND = "postgresql"
_SQLITE_MASTER_RE = re.compile(
    r"SELECT\s+(?P<select>.+?)\s+FROM\s+sqlite_master\s+WHERE\s+type\s*=\s*'(?P<object_type>table|index|view)'"
    r"(?P<rest>.*)",
    re.IGNORECASE | re.DOTALL,
)
_PRAGMA_TABLE_INFO_RE = re.compile(
    r"^\s*PRAGMA\s+table_info\((?P<table>[A-Za-z_][A-Za-z0-9_]*)\)\s*;?\s*$",
    re.IGNORECASE,
)
_STRFTIME_EXPR_RE = re.compile(
    r"strftime\(\s*'(?P<fmt>[^']+)'\s*,\s*(?P<expr>[^)]+?)\s*\)",
    re.IGNORECASE,
)
_DATE_FUNC_RE = re.compile(r"\bdate\(([^()]+?)\)", re.IGNORECASE)
_DATETIME_NOW_WITH_OFFSET_RE = re.compile(
    r"datetime\(\s*'now'\s*,\s*\?\s*\)",
    re.IGNORECASE,
)
_DATETIME_SIMPLE_RE = re.compile(r"\bdatetime\(([^()]+?)\)", re.IGNORECASE)
_JULIANDAY_RE = re.compile(r"julianday\(([^()]+?)\)", re.IGNORECASE)
_AUTOINCREMENT_RE = re.compile(
    r"\bINTEGER\s+PRIMARY\s+KEY\s+AUTOINCREMENT\b",
    re.IGNORECASE,
)
_INSERT_OR_IGNORE_RE = re.compile(r"\bINSERT\s+OR\s+IGNORE\b", re.IGNORECASE)
_GLOB_NUMERIC_RE = re.compile(
    r"TRIM\(COALESCE\((?P<expr>[^,]+?),\s*''\)\)\s+GLOB\s+'\[0-9\]\*'",
    re.IGNORECASE,
)
_INSERT_INTO_RE = re.compile(
    r"^\s*INSERT\s+INTO\s+(?P<table>[A-Za-z_][A-Za-z0-9_]*)",
    re.IGNORECASE | re.DOTALL,
)


class HybridRow(Mapping[str, Any]):
    def __init__(self, keys: list[str], values: list[Any]):
        self._keys = list(keys)
        self._values = list(values)
        self._mapping = dict(zip(self._keys, self._values))

    def __getitem__(self, key: str | int) -> Any:
        if isinstance(key, int):
            return self._values[key]
        return self._mapping[key]

    def __iter__(self) -> Iterator[str]:
        return iter(self._keys)

    def __len__(self) -> int:
        return len(self._keys)

    def keys(self):
        return self._keys

    def values(self):
        return self._values

    def items(self):
        return self._mapping.items()


def get_database_backend(*, database_url: str | None = None) -> str:
    url = (database_url or "").strip()
    if url.lower().startswith(("postgres://", "postgresql://")):
        return POSTGRES_BACKEND
    return SQLITE_BACKEND


def get_default_app_data_dir(base_dir: str | Path, *, database_url: str | None, database_path: str | Path) -> str:
    backend = get_database_backend(database_url=database_url)
    if backend == SQLITE_BACKEND:
        return str(Path(database_path).resolve().parent)
    return str((Path(base_dir) / "data").resolve())


def get_integrity_error_class(database_backend: str):
    if database_backend == POSTGRES_BACKEND:
        return PostgresIntegrityError
    return sqlite3.IntegrityError


def get_operational_error_class(database_backend: str):
    if database_backend == POSTGRES_BACKEND:
        return PostgresOperationalError
    return sqlite3.OperationalError


def normalize_sql_params(params):
    if params is None:
        return ()
    if isinstance(params, tuple):
        return params
    if isinstance(params, list):
        return tuple(params)
    return (params,)


def _replace_qmark_placeholders(sql: str) -> str:
    result: list[str] = []
    in_single_quote = False
    i = 0
    while i < len(sql):
        ch = sql[i]
        if ch == "'":
            result.append(ch)
            if in_single_quote and i + 1 < len(sql) and sql[i + 1] == "'":
                result.append("'")
                i += 2
                continue
            in_single_quote = not in_single_quote
            i += 1
            continue
        if ch == "?" and not in_single_quote:
            result.append("%s")
        else:
            result.append(ch)
        i += 1
    return "".join(result)


def _escape_psycopg_percent(sql: str) -> str:
    result: list[str] = []
    i = 0
    while i < len(sql):
        ch = sql[i]
        if ch != "%":
            result.append(ch)
            i += 1
            continue
        if i + 1 < len(sql) and sql[i + 1] in {"s", "b", "t", "%"}:
            result.append("%")
            result.append(sql[i + 1])
            i += 2
            continue
        result.append("%%")
        i += 1
    return "".join(result)


def _normalize_sql_for_postgres(sql: str) -> str:
    normalized = sql
    normalized = _AUTOINCREMENT_RE.sub("INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY", normalized)
    normalized = _INSERT_OR_IGNORE_RE.sub("INSERT INTO", normalized)
    normalized = _STRFTIME_EXPR_RE.sub(_replace_strftime_expr, normalized)
    normalized = _DATE_FUNC_RE.sub(lambda m: f"CAST({m.group(1).strip()} AS DATE)", normalized)
    normalized = _DATETIME_NOW_WITH_OFFSET_RE.sub("CURRENT_TIMESTAMP + CAST(%s AS interval)", normalized)
    normalized = _DATETIME_SIMPLE_RE.sub(lambda m: f"CAST({m.group(1).strip()} AS TIMESTAMP)", normalized)
    normalized = _JULIANDAY_RE.sub(
        lambda m: f"(EXTRACT(EPOCH FROM CAST({m.group(1).strip()} AS TIMESTAMP)) / 86400.0)",
        normalized,
    )
    normalized = _GLOB_NUMERIC_RE.sub(
        lambda m: f"TRIM(COALESCE({m.group('expr').strip()}, '')) ~ '^[0-9].*$'",
        normalized,
    )
    normalized = _replace_qmark_placeholders(normalized)
    normalized = _escape_psycopg_percent(normalized)
    return normalized


def _replace_strftime_expr(match: re.Match[str]) -> str:
    fmt = match.group("fmt")
    expr = match.group("expr").strip()
    expr_sql = "CURRENT_TIMESTAMP" if expr.lower() == "'now'" else expr
    pg_fmt = (
        fmt.replace("%Y", "YYYY")
        .replace("%m", "MM")
        .replace("%d", "DD")
        .replace("%H", "HH24")
        .replace("%M", "MI")
        .replace("%S", "SS")
    )
    return f"TO_CHAR({expr_sql}, '{pg_fmt}')"


def _append_returning_id(sql: str) -> str:
    if re.search(r"\bRETURNING\b", sql, re.IGNORECASE):
        return sql
    match = _INSERT_INTO_RE.match(sql)
    if not match:
        return sql
    return f"{sql.rstrip().rstrip(';')} RETURNING id"


def _dict_to_hybrid_row(row: dict[str, Any]) -> HybridRow:
    keys = list(row.keys())
    return HybridRow(keys, [row[key] for key in keys])


class CompatCursor:
    def __init__(self, connection: "PostgresCompatConnection", raw_cursor=None):
        self.connection = connection
        self._cursor = raw_cursor or connection._raw.cursor(row_factory=dict_row)
        self._emulated_rows: list[HybridRow] | None = None
        self.lastrowid = None
        self.rowcount = -1

    def execute(self, sql: str, params=None):
        self.lastrowid = None
        self._emulated_rows = None
        special_rows = self.connection._maybe_emulate(sql, params)
        if special_rows is not None:
            self._emulated_rows = special_rows
            self.rowcount = len(special_rows)
            return self

        normalized_sql = _normalize_sql_for_postgres(sql)
        normalized_params = normalize_sql_params(params)
        if normalized_sql.lstrip().upper().startswith("INSERT "):
            normalized_sql = _append_returning_id(normalized_sql)
            self._cursor.execute(normalized_sql, normalized_params)
            inserted_row = self._cursor.fetchone()
            self.rowcount = self._cursor.rowcount
            self.connection.total_changes += max(self.rowcount, 0)
            if inserted_row:
                hybrid = _dict_to_hybrid_row(inserted_row)
                self.lastrowid = hybrid["id"] if "id" in hybrid else None
            return self

        self._cursor.execute(normalized_sql, normalized_params)
        self.rowcount = self._cursor.rowcount
        self.connection.total_changes += max(self.rowcount, 0)
        return self

    def executemany(self, sql: str, seq_of_params):
        normalized_sql = _normalize_sql_for_postgres(sql)
        normalized_params = [normalize_sql_params(params) for params in seq_of_params]
        self._cursor.executemany(normalized_sql, normalized_params)
        self.rowcount = self._cursor.rowcount
        self.connection.total_changes += max(self.rowcount, 0)
        return self

    def fetchone(self):
        if self._emulated_rows is not None:
            if not self._emulated_rows:
                return None
            return self._emulated_rows.pop(0)

        row = self._cursor.fetchone()
        if row is None:
            return None
        return _dict_to_hybrid_row(row)

    def fetchall(self):
        if self._emulated_rows is not None:
            rows = list(self._emulated_rows)
            self._emulated_rows = []
            return rows
        return [_dict_to_hybrid_row(row) for row in self._cursor.fetchall()]

    def close(self):
        self._cursor.close()

    def __getattr__(self, item):
        return getattr(self._cursor, item)


class PostgresCompatConnection:
    def __init__(self, raw_connection):
        self._raw = raw_connection
        self.row_factory = None
        self.total_changes = 0

    def cursor(self):
        return CompatCursor(self)

    def execute(self, sql: str, params=None):
        return self.cursor().execute(sql, params)

    def executemany(self, sql: str, seq_of_params):
        return self.cursor().executemany(sql, seq_of_params)

    def commit(self):
        self._raw.commit()

    def rollback(self):
        self._raw.rollback()

    def close(self):
        self._raw.close()

    def _maybe_emulate(self, sql: str, params=None):
        pragma_match = _PRAGMA_TABLE_INFO_RE.match(sql)
        if pragma_match:
            table_name = pragma_match.group("table")
            return self._emulate_table_info(table_name)

        if "sqlite_master" in sql.lower():
            return self._emulate_sqlite_master(sql, params)
        return None

    def _emulate_table_info(self, table_name: str):
        rows = self._raw.cursor(row_factory=dict_row)
        rows.execute(
            """
            SELECT
                (cols.ordinal_position - 1) AS cid,
                cols.column_name AS name,
                cols.data_type AS type,
                CASE WHEN cols.is_nullable = 'NO' THEN 1 ELSE 0 END AS notnull,
                cols.column_default AS dflt_value,
                CASE WHEN pk.column_name IS NOT NULL THEN 1 ELSE 0 END AS pk
            FROM information_schema.columns cols
            LEFT JOIN (
                SELECT kcu.column_name
                FROM information_schema.table_constraints tc
                JOIN information_schema.key_column_usage kcu
                  ON tc.constraint_name = kcu.constraint_name
                 AND tc.table_schema = kcu.table_schema
                 AND tc.table_name = kcu.table_name
                WHERE tc.table_schema = current_schema()
                  AND tc.table_name = %s
                  AND tc.constraint_type = 'PRIMARY KEY'
            ) pk
              ON pk.column_name = cols.column_name
            WHERE cols.table_schema = current_schema()
              AND cols.table_name = %s
            ORDER BY cols.ordinal_position
            """,
            (table_name, table_name),
        )
        result = rows.fetchall()
        rows.close()
        return [_dict_to_hybrid_row(row) for row in result]

    def _emulate_sqlite_master(self, sql: str, params=None):
        match = _SQLITE_MASTER_RE.search(sql)
        if not match:
            return []

        object_type = match.group("object_type").lower()
        rest = match.group("rest") or ""
        normalized_params = list(normalize_sql_params(params))
        table_filter = None
        exclude_sqlite = "name NOT LIKE 'sqlite_%'" in rest
        order_by_name = "ORDER BY NAME" in rest.upper()

        if "name = ?" in rest and normalized_params:
            table_filter = normalized_params[0]
        elif "name=?" in rest and normalized_params:
            table_filter = normalized_params[0]

        if object_type == "table":
            base_sql = """
                SELECT table_name AS name
                FROM information_schema.tables
                WHERE table_schema = current_schema()
            """
            query_params = []
            if table_filter is not None:
                base_sql += " AND table_name = %s"
                query_params.append(table_filter)
            if exclude_sqlite:
                base_sql += " AND table_name NOT LIKE 'sqlite_%'"
            if order_by_name:
                base_sql += " ORDER BY table_name"
        elif object_type == "view":
            base_sql = """
                SELECT table_name AS name
                FROM information_schema.views
                WHERE table_schema = current_schema()
            """
            query_params = []
            if table_filter is not None:
                base_sql += " AND table_name = %s"
                query_params.append(table_filter)
            if order_by_name:
                base_sql += " ORDER BY table_name"
        else:
            base_sql = """
                SELECT indexname AS name
                FROM pg_indexes
                WHERE schemaname = current_schema()
            """
            query_params = []
            if table_filter is not None:
                base_sql += " AND indexname = %s"
                query_params.append(table_filter)
            if order_by_name:
                base_sql += " ORDER BY indexname"

        cursor = self._raw.cursor(row_factory=dict_row)
        cursor.execute(base_sql, tuple(query_params))
        rows = cursor.fetchall()
        cursor.close()

        select_clause = match.group("select").strip().upper()
        if select_clause == "1":
            return [HybridRow(["1"], [1])] if rows else []
        return [_dict_to_hybrid_row(row) for row in rows]

    def __getattr__(self, item):
        return getattr(self._raw, item)


def create_connection(
    *,
    database_url: str | None,
    database_path: str | Path,
    row_factory=False,
    uri=False,
):
    backend = get_database_backend(database_url=database_url)
    if backend == POSTGRES_BACKEND:
        if psycopg is None:
            raise RuntimeError("psycopg is required when DATABASE_URL points to PostgreSQL")
        connection = psycopg.connect(database_url)
        wrapped = PostgresCompatConnection(connection)
        wrapped.row_factory = row_factory
        return wrapped

    connection = sqlite3.connect(str(Path(database_path)), uri=uri)
    if row_factory:
        connection.row_factory = sqlite3.Row if row_factory is True else row_factory
    return connection
