import argparse
import json
import shutil
import sqlite3
from collections import defaultdict, deque
from datetime import datetime
from pathlib import Path
import re

import psycopg


DDL_AUTOINCREMENT_RE = re.compile(
    r"\bINTEGER\s+PRIMARY\s+KEY\s+AUTOINCREMENT\b",
    re.IGNORECASE,
)
DDL_INTEGER_PK_RE = re.compile(
    r"\bINTEGER\s+PRIMARY\s+KEY\b",
    re.IGNORECASE,
)
REF_RE = re.compile(r"REFERENCES\s+\"?([A-Za-z_][A-Za-z0-9_]*)\"?\s*\(", re.IGNORECASE)


def backup_sqlite_source(source_path: Path) -> Path:
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    backup_dir = source_path.parent / "backups"
    backup_dir.mkdir(parents=True, exist_ok=True)
    backup_path = backup_dir / f"{source_path.stem}.pre_postgres_migration_{timestamp}{source_path.suffix}"
    shutil.copy2(source_path, backup_path)
    return backup_path


def translate_sqlite_ddl(sql: str) -> str:
    translated = sql.replace("\n", " ")
    translated = DDL_AUTOINCREMENT_RE.sub(
        "INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
        translated,
    )
    translated = DDL_INTEGER_PK_RE.sub(
        "INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
        translated,
    )
    translated = translated.replace("INSERT OR IGNORE", "INSERT INTO")
    return translated


def load_sqlite_schema(source_conn):
    rows = source_conn.execute(
        """
        SELECT name, type, sql
        FROM sqlite_master
        WHERE type IN ('table', 'index')
          AND name NOT LIKE 'sqlite_%'
          AND sql IS NOT NULL
        ORDER BY CASE type WHEN 'table' THEN 0 ELSE 1 END, name
        """
    ).fetchall()

    tables = {}
    indexes = []
    for row in rows:
        if row["type"] == "table":
            tables[row["name"]] = row["sql"]
        else:
            indexes.append((row["name"], row["sql"]))
    return tables, indexes


def topo_sort_tables(table_ddls: dict[str, str]) -> list[str]:
    deps = {table: set() for table in table_ddls}
    reverse = defaultdict(set)

    for table, ddl in table_ddls.items():
        for ref in REF_RE.findall(ddl or ""):
            if ref in table_ddls and ref != table:
                deps[table].add(ref)
                reverse[ref].add(table)

    queue = deque(sorted([table for table, refset in deps.items() if not refset]))
    ordered = []
    while queue:
        table = queue.popleft()
        ordered.append(table)
        for child in sorted(reverse[table]):
            deps[child].discard(table)
            if not deps[child]:
                queue.append(child)

    if len(ordered) != len(table_ddls):
        remaining = sorted(set(table_ddls) - set(ordered))
        raise RuntimeError(f"Cannot resolve table dependency order: {remaining}")
    return ordered


def fetch_table_columns(source_conn, table_name: str) -> list[str]:
    rows = source_conn.execute(f"PRAGMA table_info({table_name})").fetchall()
    return [row[1] for row in rows]


def reset_target_schema(target_conn):
    with target_conn.cursor() as cursor:
        cursor.execute("DROP SCHEMA IF EXISTS public CASCADE")
        cursor.execute("CREATE SCHEMA public")
    target_conn.commit()


def create_target_schema(target_conn, table_order: list[str], table_ddls: dict[str, str], indexes: list[tuple[str, str]]):
    with target_conn.cursor() as cursor:
        for table in table_order:
            cursor.execute(translate_sqlite_ddl(table_ddls[table]))
        for _, ddl in indexes:
            cursor.execute(translate_sqlite_ddl(ddl))
    target_conn.commit()


def copy_table_data(source_conn, target_conn, table_name: str, columns: list[str], chunk_size: int = 500):
    quoted_columns = ", ".join(f'"{column}"' for column in columns)
    placeholders = ", ".join(["%s"] * len(columns))
    insert_sql = f'INSERT INTO "{table_name}" ({quoted_columns}) VALUES ({placeholders})'

    cursor = source_conn.execute(f'SELECT {quoted_columns} FROM "{table_name}"')
    copied = 0
    while True:
        batch = cursor.fetchmany(chunk_size)
        if not batch:
            break
        rows = [tuple(row[column] for column in columns) for row in batch]
        with target_conn.cursor() as target_cursor:
            target_cursor.executemany(insert_sql, rows)
        target_conn.commit()
        copied += len(rows)
    return copied


def align_identity_sequence(target_conn, table_name: str):
    with target_conn.cursor() as cursor:
        cursor.execute(
            f"""
            SELECT setval(
                pg_get_serial_sequence(%s, 'id'),
                COALESCE((SELECT MAX(id) FROM "{table_name}"), 1),
                (SELECT MAX(id) IS NOT NULL FROM "{table_name}")
            )
            """,
            (table_name,),
        )
    target_conn.commit()


def migrate(source_path: Path, target_url: str, *, reset_target: bool, report_path: Path | None):
    if not source_path.exists():
        raise FileNotFoundError(f"SQLite source not found: {source_path}")

    backup_path = backup_sqlite_source(source_path)
    source_conn = sqlite3.connect(source_path)
    source_conn.row_factory = sqlite3.Row
    target_conn = psycopg.connect(target_url)

    try:
        tables, indexes = load_sqlite_schema(source_conn)
        table_order = topo_sort_tables(tables)

        if reset_target:
            reset_target_schema(target_conn)
        create_target_schema(target_conn, table_order, tables, indexes)

        copied_rows = {}
        for table_name in table_order:
            columns = fetch_table_columns(source_conn, table_name)
            copied_rows[table_name] = copy_table_data(source_conn, target_conn, table_name, columns)
            if "id" in columns:
                align_identity_sequence(target_conn, table_name)

        report = {
            "source": str(source_path),
            "backup": str(backup_path),
            "target": target_url,
            "reset_target": reset_target,
            "tables": copied_rows,
            "index_count": len(indexes),
            "finished_at": datetime.now().isoformat(timespec="seconds"),
        }
        if report_path:
            report_path.parent.mkdir(parents=True, exist_ok=True)
            report_path.write_text(json.dumps(report, ensure_ascii=False, indent=2), encoding="utf-8")
        return report
    finally:
        source_conn.close()
        target_conn.close()


def main():
    parser = argparse.ArgumentParser(description="Migrate SQLite station_monitor.db into PostgreSQL")
    parser.add_argument("--source", default="station_monitor.db", help="SQLite source database path")
    parser.add_argument("--target-url", required=True, help="PostgreSQL DATABASE_URL")
    parser.add_argument("--no-reset-target", action="store_true", help="Keep existing PostgreSQL public schema")
    parser.add_argument("--report", help="Optional JSON report path")
    args = parser.parse_args()

    report = migrate(
        Path(args.source).resolve(),
        args.target_url,
        reset_target=not args.no_reset_target,
        report_path=Path(args.report).resolve() if args.report else None,
    )
    print(json.dumps(report, ensure_ascii=False, indent=2))


if __name__ == "__main__":
    main()
