"""PostgreSQL 兼容层测试 — 需要 DATABASE_URL 指向真实 PostgreSQL 实例。

运行方式：
    DATABASE_URL="postgresql://user:pass@localhost/dbname" pytest -m postgres -v

如果没有可用的 PostgreSQL，这些测试会被跳过。
"""
import os

import pytest

# 没有 DATABASE_URL 时整个模块跳过
DATABASE_URL = os.environ.get("DATABASE_URL", "")
_pg_available = DATABASE_URL.startswith("postgresql://")

pytestmark = pytest.mark.postgres

if not _pg_available:
    pytestmark = pytest.mark.skip(reason="DATABASE_URL not set or not PostgreSQL")


@pytest.fixture
def pg_conn():
    """创建 PostgreSQL 连接用于兼容层测试"""
    from db import create_connection, close_pool

    conn = create_connection(
        database_url=DATABASE_URL,
        database_path="",  # PostgreSQL 忽略此参数
        row_factory=True,
    )
    yield conn
    try:
        conn.close()
    except Exception:
        pass
    close_pool()


@pytest.fixture
def pg_clean_db(pg_conn):
    """创建干净的测试表环境"""
    pg_conn.execute("DROP TABLE IF EXISTS _test_compat")
    pg_conn.execute("DROP TABLE IF EXISTS _test_upsert")
    pg_conn.commit()
    yield pg_conn
    pg_conn.execute("DROP TABLE IF EXISTS _test_compat")
    pg_conn.execute("DROP TABLE IF EXISTS _test_upsert")
    pg_conn.commit()


# ============================================================
# 1. 基本连接与查询
# ============================================================


def test_basic_select(pg_conn):
    """基本 SELECT 查询"""
    result = pg_conn.execute("SELECT 1 AS val").fetchone()
    assert result["val"] == 1


def test_parameterized_query(pg_conn):
    """参数化查询（? 占位符自动转换为 %s）"""
    result = pg_conn.execute(
        "SELECT ? AS a, ? AS b",
        ("hello", 42),
    ).fetchone()
    assert result["a"] == "hello"
    assert result["b"] == 42


def test_row_factory_dict_access(pg_conn):
    """行结果支持字典式访问"""
    result = pg_conn.execute("SELECT 1 AS id, 'test' AS name").fetchone()
    assert result["id"] == 1
    assert result["name"] == "test"


# ============================================================
# 2. DDL 与 CRUD
# ============================================================


def test_create_table_and_insert(pg_clean_db):
    """CREATE TABLE + INSERT + SELECT"""
    conn = pg_clean_db
    conn.execute("""
        CREATE TABLE _test_compat (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            name TEXT NOT NULL,
            value INTEGER DEFAULT 0
        )
    """)
    conn.commit()

    conn.execute("INSERT INTO _test_compat (name, value) VALUES (?, ?)", ("alpha", 10))
    conn.execute("INSERT INTO _test_compat (name, value) VALUES (?, ?)", ("beta", 20))
    conn.commit()

    rows = conn.execute("SELECT name, value FROM _test_compat ORDER BY name").fetchall()
    assert len(rows) == 2
    assert rows[0]["name"] == "alpha"
    assert rows[1]["value"] == 20


def test_update_and_delete(pg_clean_db):
    """UPDATE / DELETE 操作"""
    conn = pg_clean_db
    conn.execute("""
        CREATE TABLE _test_compat (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            name TEXT NOT NULL,
            status TEXT DEFAULT 'active'
        )
    """)
    conn.commit()

    conn.execute("INSERT INTO _test_compat (name) VALUES (?)", ("item1",))
    conn.execute("INSERT INTO _test_compat (name) VALUES (?)", ("item2",))
    conn.commit()

    conn.execute("UPDATE _test_compat SET status = ? WHERE name = ?", ("closed", "item1"))
    conn.commit()

    active = conn.execute("SELECT COUNT(*) AS cnt FROM _test_compat WHERE status = 'active'").fetchone()
    assert active["cnt"] == 1


# ============================================================
# 3. SQLite → PostgreSQL SQL 翻译
# ============================================================


def test_autoincrement_translation(pg_clean_db):
    """INTEGER PRIMARY KEY AUTOINCREMENT 应被翻译为 GENERATED BY DEFAULT AS IDENTITY"""
    conn = pg_clean_db
    # 这条 SQL 包含 AUTOINCREMENT 关键词
    conn.execute("""
        CREATE TABLE _test_compat (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            label TEXT
        )
    """)
    conn.commit()

    conn.execute("INSERT INTO _test_compat (label) VALUES (?)", ("row1",))
    conn.execute("INSERT INTO _test_compat (label) VALUES (?)", ("row2",))
    conn.commit()

    rows = conn.execute("SELECT id, label FROM _test_compat ORDER BY id").fetchall()
    assert rows[0]["id"] == 1
    assert rows[1]["id"] == 2


def test_strftime_translation(pg_clean_db):
    """strftime('%Y-%m', ...) 应被翻译为 TO_CHAR(..., 'YYYY-MM')"""
    conn = pg_clean_db
    conn.execute("""
        CREATE TABLE _test_compat (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        )
    """)
    conn.commit()

    conn.execute("INSERT INTO _test_compat (id) VALUES (1)")
    conn.commit()

    row = conn.execute(
        "SELECT strftime('%Y', created_at) AS year FROM _test_compat WHERE id = ?",
        (1,),
    ).fetchone()
    assert row["year"] is not None
    assert len(row["year"]) == 4  # 四位年份


def test_statistics_style_group_by_expressions_work_in_postgres(pg_clean_db):
    """统计接口常见聚合写法在 PostgreSQL 兼容层下应可正常执行"""
    conn = pg_clean_db
    conn.execute("""
        CREATE TABLE stations (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            name TEXT NOT NULL,
            county TEXT,
            voltage_level TEXT
        )
    """)
    conn.execute("""
        CREATE TABLE fault_reports (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            station_id INTEGER NOT NULL,
            created_at TIMESTAMP NOT NULL,
            fault_group_key TEXT,
            status TEXT,
            camera_id INTEGER
        )
    """)
    conn.commit()

    conn.execute(
        "INSERT INTO stations (id, name, county, voltage_level) VALUES (1, '测试变电站', '测试县', '220kV')"
    )
    conn.executemany(
        """
        INSERT INTO fault_reports (id, station_id, created_at, fault_group_key, status, camera_id)
        VALUES (?, ?, ?, ?, ?, ?)
        """,
        [
            (1, 1, '2026-04-25 10:00:00', 'group-a', 'open', 101),
            (2, 1, '2026-04-25 10:05:00', 'group-a', 'handling', 101),
            (3, 1, '2026-04-26 09:00:00', None, 'closed', 102),
        ],
    )
    conn.commit()

    month_expr = "strftime('%Y-%m', f.created_at)"
    county_expr = "COALESCE(NULLIF(TRIM(s.county), ''), '未知')"
    voltage_level_expr = "COALESCE(NULLIF(TRIM(s.voltage_level), ''), '其他')"
    fault_group_key_expr = "COALESCE(NULLIF(TRIM(f.fault_group_key), ''), CAST(f.id AS TEXT))"
    camera_location_expr = "COALESCE(NULLIF(TRIM(CAST(f.camera_id AS TEXT)), ''), '未命名设备')"

    monthly_rows = conn.execute(
        f"""
        SELECT {month_expr} AS month, COUNT(*) AS cnt
        FROM fault_reports f
        WHERE strftime('%Y', f.created_at) = ?
        GROUP BY {month_expr}
        """,
        ('2026',),
    ).fetchall()
    assert len(monthly_rows) == 1
    assert monthly_rows[0]['month'] == '2026-04'
    assert monthly_rows[0]['cnt'] == 3

    monthly_event_rows = conn.execute(
        f"""
        SELECT event_month AS month, COUNT(*) AS cnt
        FROM (
            SELECT
                {month_expr} AS event_month,
                {fault_group_key_expr} AS fault_event_key
            FROM fault_reports f
            WHERE strftime('%Y', f.created_at) = ?
            GROUP BY {month_expr}, {fault_group_key_expr}
        ) deduped
        GROUP BY event_month
        """,
        ('2026',),
    ).fetchall()
    assert len(monthly_event_rows) == 1
    assert monthly_event_rows[0]['month'] == '2026-04'
    assert monthly_event_rows[0]['cnt'] == 2

    county_rows = conn.execute(
        f"""
        SELECT
            records.county,
            records.count,
            events.event_count
        FROM (
            SELECT
                {county_expr} AS county,
                COUNT(*) AS count
            FROM fault_reports f
            JOIN stations s ON f.station_id = s.id
            GROUP BY {county_expr}
        ) records
        JOIN (
            SELECT
                deduped.county,
                COUNT(*) AS event_count
            FROM (
                SELECT
                    {county_expr} AS county,
                    {fault_group_key_expr} AS fault_event_key
                FROM fault_reports f
                JOIN stations s ON f.station_id = s.id
                GROUP BY {county_expr}, {fault_group_key_expr}
            ) deduped
            GROUP BY deduped.county
        ) events ON events.county = records.county
        """
    ).fetchall()
    assert len(county_rows) == 1
    assert county_rows[0]['county'] == '测试县'
    assert county_rows[0]['count'] == 3
    assert county_rows[0]['event_count'] == 2

    voltage_rows = conn.execute(
        f"""
        SELECT {voltage_level_expr} AS voltage_level, COUNT(*) AS count
        FROM fault_reports f
        JOIN stations s ON f.station_id = s.id
        GROUP BY {voltage_level_expr}
        """
    ).fetchall()
    assert len(voltage_rows) == 1
    assert voltage_rows[0]['voltage_level'] == '220kV'
    assert voltage_rows[0]['count'] == 3

    camera_ranking_rows = conn.execute(
        f"""
        SELECT
            records.camera_id,
            records.camera_location,
            records.fault_count,
            events.fault_event_count
        FROM (
            SELECT
                f.camera_id,
                {camera_location_expr} AS camera_location,
                COUNT(*) AS fault_count
            FROM fault_reports f
            WHERE f.camera_id IS NOT NULL
            GROUP BY f.camera_id, {camera_location_expr}
        ) records
        JOIN (
            SELECT
                f.camera_id,
                COUNT(DISTINCT {fault_group_key_expr}) AS fault_event_count
            FROM fault_reports f
            WHERE f.camera_id IS NOT NULL
            GROUP BY f.camera_id
        ) events ON events.camera_id = records.camera_id
        ORDER BY records.camera_id
        """
    ).fetchall()
    assert len(camera_ranking_rows) == 2
    assert camera_ranking_rows[0]['camera_id'] == 101
    assert camera_ranking_rows[0]['fault_count'] == 2
    assert camera_ranking_rows[0]['fault_event_count'] == 1




def test_connection_pool_reuse():
    """多次 getconn 应返回不同但可复用的连接"""
    from db import _get_or_create_pool, close_pool

    pool = _get_or_create_pool(DATABASE_URL)
    conn1 = pool.getconn()
    conn2 = pool.getconn()
    # 不同连接
    assert conn1 is not conn2
    pool.putconn(conn1)
    pool.putconn(conn2)


def test_connection_pool_basics():
    """连接池基本状态"""
    from db import _get_or_create_pool, close_pool

    pool = _get_or_create_pool(DATABASE_URL)
    assert not pool.closed
    assert pool.min_size >= 1
    assert pool.max_size >= pool.min_size


def test_close_pool():
    """关闭连接池后重建"""
    from db import close_pool, _get_or_create_pool

    pool1 = _get_or_create_pool(DATABASE_URL)
    close_pool()
    pool2 = _get_or_create_pool(DATABASE_URL)
    assert pool2 is not pool1
    close_pool()


# ============================================================
# 5. lastrowid
# ============================================================


def test_lastrowid(pg_clean_db):
    """INSERT 后 lastrowid 应返回自增 ID"""
    conn = pg_clean_db
    conn.execute("""
        CREATE TABLE _test_compat (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            name TEXT
        )
    """)
    conn.commit()

    cursor = conn.execute("INSERT INTO _test_compat (name) VALUES (?)", ("test",))
    assert cursor.lastrowid is not None
    assert cursor.lastrowid >= 1
    conn.commit()
